- name: Copy configuration files
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Delete default site configuration
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Nginx config file
      ansible.builtin.template:
        src: ../config/django.conf
        dest: /etc/nginx/sites-available/django.conf
        mode: "0644"
      register: nginx_config

    - name: Create well-known directory (for Certbot)
      ansible.builtin.file:
        path: /var/www/django-app/.well-known
        state: directory
        mode: "0755"

    - name: Nginx main config file
      ansible.builtin.template:
        src: ../config/nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: "0644"

    - name: Nginx config file symlink
      ansible.builtin.file:
        src: /etc/nginx/sites-available/django.conf
        dest: /etc/nginx/sites-enabled/django.conf
        state: link

    - name: UWSGI config file
      ansible.builtin.template:
        src: ../config/example_project.ini
        dest: /etc/uwsgi/apps-enabled/example_project.ini
        mode: "0644"
      register: uwsgi_config

    - name: Nginx restart
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: UWSGI restart
      ansible.builtin.service:
        name: uwsgi
        state: restarted
